version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: dataphp
      MYSQL_PASSWORD: sasa
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    restart: always
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: sasa
    ports:
      - "8080:80"

volumes:
  db_data:
